package it.polito.cloudresources.be.config.persist;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.core.annotation.Order;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

/**
 * Automatically migrates the database schema for SSH Keys
 * to support the transition from 1:1 to 1:N relationship.
 * Executed at application startup.
 */
@Component
@Order(1) // Ensures this runs before other startup logic
@RequiredArgsConstructor
@Slf4j
public class SshKeyMigrationRunner implements CommandLineRunner {

    private final JdbcTemplate jdbcTemplate;

    @Override
    @Transactional
    public void run(String... args) throws Exception {
        log.info("Checking SSH Key database schema migration...");

        // 1. Add 'label' column if it doesn't exist
        try {
            // Using PostgreSQL syntax
            jdbcTemplate.execute("ALTER TABLE ssh_keys ADD COLUMN IF NOT EXISTS label VARCHAR(255)");
            log.info("Column 'label' check/add completed for table 'ssh_keys'.");
        } catch (Exception e) {
            log.error("Error ensuring column 'label' exists: {}", e.getMessage());
        }

        // 2. Set 'Default' label for existing legacy keys (Data Migration)
        try {
            int updated = jdbcTemplate.update("UPDATE ssh_keys SET label = 'Default' WHERE label IS NULL");
            if (updated > 0) {
                log.info("Migrated {} legacy SSH keys: label set to 'Default'.", updated);
            }
        } catch (Exception e) {
            log.error("Error updating legacy keys data: {}", e.getMessage());
        }

        // 3. Remove UNIQUE constraint on user_id to allow multiple keys
        // We must query the catalog first because the constraint name is auto-generated by Hibernate
        try {
            String findConstraintSql =
                "SELECT con.conname " +
                "FROM pg_catalog.pg_constraint con " +
                "INNER JOIN pg_catalog.pg_class rel ON rel.oid = con.conrelid " +
                "INNER JOIN pg_catalog.pg_namespace nsp ON nsp.oid = connamespace " +
                "WHERE nsp.nspname = 'public' " +
                "AND rel.relname = 'ssh_keys' " +
                "AND con.contype = 'u'"; // 'u' = unique constraint

            List<String> constraints = jdbcTemplate.queryForList(findConstraintSql, String.class);

            for (String constraintName : constraints) {
                // We assume any unique constraint on this table (other than PK) is the one on user_id 
                // that we want to remove to allow 1:N.
                log.info("Dropping unique constraint '{}' to enable multi-key support...", constraintName);
                jdbcTemplate.execute("ALTER TABLE ssh_keys DROP CONSTRAINT " + constraintName);
                log.info("Constraint dropped successfully.");
            }
            
            if (constraints.isEmpty()) {
                log.info("No unique constraints found on 'ssh_keys'. Multi-key support is already active.");
            }

        } catch (Exception e) {
            log.warn("Warning during constraint removal (might already be removed): {}", e.getMessage());
        }
        
        log.info("SSH Key schema migration check completed.");
    }
}